# Use mcr.microsoft.com/devcontainers/python:3.12 as the base image
FROM mcr.microsoft.com/devcontainers/python:3.12

# Install any additional dependencies if needed
# Example: RUN apt-get update && apt-get install -y <package-name>
RUN apt-get update && apt-get install -y uv
